Changes to the Customer Zone UI
Paymenter/Paymenter pull request #128
Opened 2023-08-11 21:52 UTC by mscodepl

Changes to the Customer Zone UI (Invoices to be paid, list of active services)

![image](https://github.com/Paymenter/Paymenter/assets/41286754/c635fc37-90f1-456c-96ab-c9065975b3c3)

2023-08-11 21:54 UTC, mscodepl commented
The button to pay is as TODO, need to add a redirect to it straight to the invoice for this products

2023-08-11 23:25 UTC, mscodepl commented
![image](https://github.com/Paymenter/Paymenter/assets/41286754/e9dc6a25-ba2c-4f3d-9762-754ea7fe0d18)
![image](https://github.com/Paymenter/Paymenter/assets/41286754/142cc173-18d9-420c-bc0a-fdb7e25378b3)
![image](https://github.com/Paymenter/Paymenter/assets/41286754/b6985b41-6e5d-430e-9d30-fe3d43e50ec9)

2023-08-11 23:28 UTC, mscodepl commented
![image](https://github.com/Paymenter/Paymenter/assets/41286754/7304a807-f3b5-41e2-b79f-a8172edcf37b)

2023-08-11 23:54 UTC, mscodepl commented
![image](https://github.com/Paymenter/Paymenter/assets/41286754/d7b360b5-4e42-46eb-859d-45e5130a1706)

2023-08-12 00:32 UTC, mscodepl commented
+ Added invoices to the admin menu
![image](https://github.com/Paymenter/Paymenter/assets/41286754/6761266b-c78e-48a9-b3e8-1e2ac8b335d7)

![image](https://github.com/Paymenter/Paymenter/assets/41286754/a4c50e13-9001-418c-958d-03eadf9e64f7)

2023-08-12 01:14 UTC, mscodepl commented
**TODO**
- [ ] Transfer showTicketDate function to Ticket

2023-08-12 05:46 UTC, CorwinDev requested changes

2023-08-12 05:46 UTC, CorwinDev commented on themes/default/views/admin/tickets/show.blade.php
> +        <form method="POST" action="{{ route('clients.tickets.reply', $ticket->id) }}" class="mt-10" id="reply">
This should be admin.tickets.reply and not clients.tickets.reply

2023-08-12 11:59 UTC, CorwinDev approved these changes

2023-08-12 12:01 UTC, merged