Changes (Corrected/Added)
Paymenter/Paymenter pull request #136
Opened 2023-08-21 22:21 UTC by mscodepl

ADDED:
1. Username input on registration, for creating eg. Pterodactyl account
2. Pterodcatyl -> Variable Server Name

2023-08-22 21:39 UTC, mscodepl commented
That's all for today :) @CorwinDev

2023-08-23 06:50 UTC, CorwinDev requested changes

2023-08-23 06:50 UTC, CorwinDev commented on app/Console/Commands/User/Create.php
> +            [$user->name, $user->email, $user->role->name, $user->username],
Should be `$user->lastname` instead of `$user->username`

2023-08-23 06:50 UTC, CorwinDev commented on themes/default/views/admin/clients/products.blade.php
> +                <x-input type="date" name="expiry_date" id="expiry_date" value="{{ $orderProduct->expiry_date->format('Y-m-d') }}"
Remove format

2023-08-23 06:50 UTC, CorwinDev commented on themes/default/views/admin/orders/show.blade.php
> +                            {{ $product->expiry_date->format('Y-m-d') ?: 'N/A' }}
Remove format

2023-08-23 06:50 UTC, CorwinDev commented on themes/default/views/admin/orders/show.blade.php
> +                                   value="{{ $product->expiry_date->format('Y-m-d') }}"
Remove format

2023-08-23 06:50 UTC, CorwinDev commented on themes/default/views/clients/products/view.blade.php
> +                            <p><span class="font-bold">{{ __('Due Date') }}: </span>{{ $orderProduct->expiry_date->format('Y-m-d') }}
Remove format

2023-08-23 15:07 UTC, CorwinDev approved these changes

2023-08-23 15:07 UTC, merged