Support for Configurable Options in VirtFusion Extension
Paymenter/Paymenter pull request #476
Opened 2024-07-10 15:49 UTC by imgucciwz

Compatibility Update: Support for Configurable Options in VirtFusion Extension
New Features:

Added support for the following configurable options in the VirtFusion API:
- hypervisorId
- ipv4
- storage
- traffic
- memory
- cpuCores
- networkSpeedInbound
- networkSpeedOutbound
- storageProfile
- networkProfile
- firewallRulesets
- additionalStorage1Enable
- additionalStorage2Enable
- additionalStorage1Profile
- additionalStorage2Profile
- additionalStorage1Capacity
- additionalStorage2Capacity
 

The Default Hypervisor Group ID input will be disregarded when a hypervisorId option is configured, ensuring proper prioritization and handling of hypervisor settings.

2024-07-12 09:17 UTC, CorwinDev commented
Why did you remove the IPs option?

2024-07-12 13:21 UTC, imgucciwz commented
> Why did you remove the IPs option?

It's not necessary to create a VPS since VirtFusion already includes this feature when you create the plan package. If you need an additional IPs, you can simply add it as a configurable option.

2024-07-16 07:21 UTC, CorwinDev requested changes

2024-07-16 07:21 UTC, CorwinDev commented on app/Extensions/Servers/VirtFusion/VirtFusion.php
> +                'friendlyName' => 'Default Hypervisor Group ID (if no hypervisorId Configurable Options)',
Please remove this `(if no hypervisorId Configurable Options)`

2024-07-18 15:05 UTC, merged